stages:
  - build
  - deploy

variables:
  IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA

build-image:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build -t $IMAGE .
    - docker push $IMAGE

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
  script:
    - chmod 600 $EC2_SSH_KEY
    - ssh -o StrictHostKeyChecking=no -i $EC2_SSH_KEY ubuntu@$EC2_PUBLIC_IP "./deploy.sh $IMAGE"
  only:
    - main
