image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: your-dockerhub-username/federated-fraud-detection:$CI_COMMIT_SHA

stages:
  - build
  - deploy

before_script:
  - apk add --no-cache git       # install git in docker image

build:
  stage: build
  tags:
    - docker
    - ubuntu
  script:
    - git clone https://github.com/tada-lala/Fraud-Detection-Using-Federated-Learning.git
    - cd Fraud-Detection-Using-Federated-Learning
    - docker build -t $IMAGE_NAME .
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  tags:
    - docker
    - ubuntu
  script:
    - docker pull $IMAGE_NAME
    - docker stop federated-fraud-app || true
    - docker rm federated-fraud-app || true
    - docker run -d --name federated-fraud-app -p 5000:5000 $IMAGE_NAME
