stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/<your-namespace>/fraud-flask-app:latest
  SSH_USER: <your_vm_user>
  SSH_HOST: <your_vm_external_ip>
  SSH_KEY: $GCP_VM_SSH_KEY  # Add your private SSH key in GitLab CI/CD variables

# -------------- BUILD IMAGE --------------
build:
  stage: build
  image: docker:24.0.5  # Docker-in-Docker
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info
  script:
    - docker build -t $DOCKER_IMAGE .
    - echo "$CI_JOB_TOKEN" | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com
    - docker push $DOCKER_IMAGE

# -------------- DEPLOY TO VM --------------
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client bash
  script:
    # Add SSH key
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    # SSH to VM and pull & restart container
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "
        docker pull $DOCKER_IMAGE &&
        docker stop fraud-flask-app || true &&
        docker rm fraud-flask-app || true &&
        docker run -d --name fraud-flask-app -p 80:8000 $DOCKER_IMAGE
      "
  only:
    - main
