stages:
  - build
  - test
  - deploy

variables:
  DOCKER_IMAGE: registry.gitlab.com/yourusername/fraud-detection-app:latest

build:
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE

test:
  stage: test
  image: python:3.11
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python -m pytest --maxfail=1 --disable-warnings

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploy your Docker container to server or Kubernetes here"
